package br.com.jpdev01.asaassdk.utils;

public enum PaymentStatus {

    PENDING,
    CONFIRMED,
    RECEIVED,
    OVERDUE,
    REFUNDED,
    RECEIVED_IN_CASH,
    REFUND_REQUESTED,
    REFUND_IN_PROGRESS,
    CHARGEBACK_REQUESTED,
    CHARGEBACK_DISPUTE,
    AWAITING_CHARGEBACK_REVERSAL,
    CHARGEBACK,
    REFUNDED_PARTIALLY,
    DUNNING_REQUESTED,
    DUNNING_RECEIVED,
    AWAITING_RISK_ANALYSIS,
    AUTHORIZED
}
