name: Sonarqube Scan Test

on:
  pull_request:
    branches:
      - sonnar

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SonarScanner
        run: |
          wget https://cdn3.gnarususercontent.com.br/3361-desenvolvimento-seguro/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip

      - name: Run SonarScanner
        run: |
            ./sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -X \
               -Dsonar.projectKey=AsaasSdk \
               -Dsonar.sources=. \
               -Dsonar.host.url=$SONARQUBE_AWS_HOST \
               -Dsonar.login=$SONARQUBE_TOKEN
        env:
          SONARQUBE_AWS_HOST: ${{ secrets.SONARQUBE_AWS_HOST }}
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}